# Generated by Django 4.0.1 on 2022-01-22 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
